### ISSUE TITLE
Is this still being updated?

### ISSUE THREAD

**Issue by Mike-Remoni** [mj1856/SqlServerTimeZoneSupport#37]
Hello everyone, 

This project is exactly what I am looking for, since I need to convert the IANA tz standard in SQL.

However, the project seems to be abandoned, as no updates or pulls have been done for a couple of years. 

If you are still around, may I ask you about how to use the database? I can't seem to get the SqlTzLoader.exe populator working.

Cheers, Mike

**Comment by jscowen** [comment]
I can't answer your questions but I also had issues with the SqlTzLoader.exe populator today, but I managed to get it all working.

Firstly I got an error about the temp folder - found I needed to manually create the folder for it, i.e. C:\Users\<username\AppData\Local\Temp\2 

Next I got a database error and found that I needed to put the database connection information in the SqlTzLoader.exe.config file as well as specify it on the command line.

Hope that helps you out...

**Comment by mattjohnsonpint** [comment]
It's just been super low priority for me.  I'll see if I can find some time to focus on it in the upcoming months.  I agree it needs some attention.

Generally, I prefer to do time zone conversions in the application layer when possible.  Also, SQL Server's `AT TIME ZONE` does a pretty good job, albeit with Windows time zone identifiers.  You can use [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) or similar packages to convert identifiers from IANA to Windows.

**Comment by californiacal** [comment]
My use case was angular 3 js time problems preventing expansion from OH to West Coast (silicon valley) new business region because of problems with offsets in the application layer not functioning properly when the timestamps were running on a UTC offset paradigm. Running the .Net platform in Azure with SQL Server backend. Always made sense to do front end application layer work, but in the case of the List<T> removing items by time..... Got ugly..... Wanted SQL Server..... And ended up using this for a minute.... So it got me out of a jam.

**Comment by mattjohnsonpint** [comment]
Glad it helped. 👍

**Comment by mattjohnsonpint** [comment]
See #40
